project_name: MkDocs
pages:
- ['index.md', 'Introduction']
- ['user-guide/writing-your-docs.md', 'User Guide / Writing your docs']
- ['user-guide/styling-your-docs.md', 'User Guide / Styling your docs']
- ['user-guide/configuration.md', 'User Guide / Configuration']
- ['about/license.md', 'About / License']
#theme_dir: 'theme'
theme: 'cerulean'
